# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import style.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style', '0002_auto_20151226_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstyle',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentstyle',
            name='css',
            field=models.FileField(default=None, upload_to=style.models.get_cssfile_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentstyle',
            name='docx',
            field=models.FileField(default=None, upload_to=style.models.get_docxfile_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentstyle',
            name='latexcls',
            field=models.FileField(default=None, upload_to=style.models.get_latexClsfile_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentstyle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
