# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0004_auto_20161113_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstyle',
            name='css',
        ),
    ]
