# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import style.models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0007_auto_20161113_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstyle',
            name='css',
            field=models.FileField(null=True, upload_to=style.models.get_cssfile_path),
        ),
    ]
