# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0008_documentstyle_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstyle',
            name='added',
        ),
        migrations.RemoveField(
            model_name='documentstyle',
            name='css',
        ),
        migrations.RemoveField(
            model_name='documentstyle',
            name='docx',
        ),
        migrations.RemoveField(
            model_name='documentstyle',
            name='latexcls',
        ),
        migrations.RemoveField(
            model_name='documentstyle',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='documentstyle',
            name='uploader',
        ),
    ]
