# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import style.models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0010_auto_20161113_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstyle',
            name='css',
            field=models.FileField(blank=True, null=True, upload_to=style.models.get_cssfile_path),
        ),
        migrations.AlterField(
            model_name='documentstyle',
            name='latexcls',
            field=models.FileField(blank=True, null=True, upload_to=style.models.get_latexClsfile_path),
        ),
        migrations.AlterField(
            model_name='documentstyle',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
