# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import style.models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0011_auto_20161113_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstyle',
            name='docx',
            field=models.FileField(blank=True, null=True, upload_to=style.models.get_docxfile_path),
        ),
    ]
