# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0012_auto_20161113_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstyle',
            name='filename',
        ),
    ]
