# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0013_remove_documentstyle_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstyle',
            name='filename',
            field=models.SlugField(blank=True, help_text=b'The base of the filenames the style occupies.', max_length=20),
        ),
    ]
